apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-test-label-token
  labels:
    app: ehr-spring-security
    cocreate.io/approved: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-test-label-token
  template:
    metadata:
      labels:
        app: ehr-test-label-token
        cocreate.io/approved: "true"
    spec:
      containers:
        - name: ehr-spring-security
          image: ghcr.io/devamatha/ehr-spring-security:latest
          ports:
            - containerPort: 8080
          env:
            - name: COCREATE_WORKLOAD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cocreate-workload-token
                  key: token
      volumes:
        - name: workload-token
          secret:
            secretName: cocreate-workload-token
