apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-spring-security-no-token
  labels:
    app: ehr-spring-security-no-token
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-spring-security-no-token
  template:
    metadata:
      labels:
        app: ehr-spring-security-no-token
    spec:
      containers:
        - name: ehr-spring-security
          image: ghcr.io/devamatha/ehr-spring-security:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
