apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-test-label-only
  labels:
    app: ehr-spring-security
    cocreate.io/approved: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-test-label-only
  template:
    metadata:
      labels:
        app: ehr-test-label-only
        cocreate.io/approved: "true"
    spec:
      containers:
        - name: ehr-spring-security
          image: ghcr.io/devamatha/ehr-spring-security:latest
          ports:
            - containerPort: 8080
